### ISSUE TITLE
should impose file size limits and # of tree limits on phylesystem

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/peyotl#103]
These constraints should be config-file dependent so that we can tweak them in the future w/o touching the code.

Looks like our biggest study is 18M, FWIW (study pg_227).

**Comment by snacktavish** [comment]
Would a nexson size check in the phylesystem-api __finish_write_verb work as a backstop?
https://github.com/OpenTreeOfLife/phylesystem-api/blob/master/controllers/default.py#L248

**Comment by mtholder** [comment]
that would get everything going through the phylesystem-api, which is good. But it it tougher to impose the filesize limit there, because the object has not been written out to the filesystem at that point.
implementing it in peyotl is a little nicer because if we ever have to run a server-side fix using peyotl (but not the phylesystem-api), then peyotl would enforce our constraints on the contents of the corpus.

**Comment by mtholder** [comment]
but the phylesystem-api (and in the spot that you highlighted @snacktavish ) may be the easiest spot to enforce a limit on the # of trees.
The phylesystem functions in peyotl are separate from the validation code. they are just versioning blobs of JSON. So, it would be awkward to put the # of trees check in the phylesystem part of peyotl.
It might be nice to have the # of trees check in the peyotl validator, though. Not sure...

**Comment by snacktavish** [comment]
So it could be an optional validaton requirement? Because presumably the peyotl validator should also ok valid nexson that is too big for phylesystem, in case people start using nexson for their other phylogenetic needs?

**Comment by mtholder** [comment]
fixed in https://github.com/OpenTreeOfLife/peyotl/pull/104
