### ISSUE TITLE
HTTP and HTTPS responses (docstore state) will "drift" over time

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/peyotl#131]
@mtholder, this is a follow-up to our recent puzzle over HTTP and HTTPS responses. As you had suggested, it seems the problem is in fact multiple instances of docstore objects that should be singletons. Compare the responses to these cURL calls, one sent via HTTP:
```bash
curl 'http://devapi.opentreeoflife.org/v2/collections/find_collections' \
    -X POST \
    -o http.json
```
... and the other sent via HTTPS:
```bash
curl 'https://devapi.opentreeoflife.org/v2/collections/find_collections' \
    -X POST \
    -o https.json
```
No difference other than the scheme, but two quite different responses from the same docstore. And in this case, there's no web2py RAM cache involved, or any other caching that I can see.

I believe there's just one running instance of web2py+peyotl on devapi (ot10):
```bash
$ ssh ot10
$ ps -x -l | grep web2py
5  1002 10746 12553  20   0 1209204 148244 ?    Sl   ?          4:10 (wsgi:web2py)     -k graceful
0  1002 28364 28293  20   0  11108   708 -      S+   pts/3      0:00 grep web2py
``` 

But as you suggested, I've added a special extension to the URL (just on devapi, not in git) to test the identify of the collections docstore object using `id()`. This appends a final element to the JSON response, a string in the form `"docstore_id: 140168092998288"` with the persistent ID of the docstore "singleton". I'm getting a very consistent value for this over a series of HTTP requests, and a different (but also consistent) value over HTTPS requests. It seems this is the problem, ie, each docstore "singleton" has its own state and does not expect to be one of _n_ instances.

You can see this for yourself by adding `/test` to the cURL calls above, for HTTP:
```bash
curl 'http://devapi.opentreeoflife.org/v2/collections/find_collections/test' \
    -X POST \
    -o http-test.json
```
... and HTTPS:
```bash
curl 'https://devapi.opentreeoflife.org/v2/collections/find_collections/test' \
    -X POST \
    -o https-test.json
```
Search the output files for "docstore" to see the different id values. I don't know if there's any way to consolidate these. I gather this is a side effect of web2py's WSGI setup...?

So is this a serious problem? Apparently not, **if** we restrict all API callers to HTTPS. Hopefully there's a more elegant solution that I'm missing. Thoughts?

Note that this will probably be "fixed" again by restarting apache, as we've seen before. I'm guessing this is because each docstore single starts by creating its internal indexes to docids based on the git repo on filesystem. Restart apache puts them back in sync, but any edits will throw the two schemes out of sync again.

**Comment by mtholder** [comment]
nice job sorting all of that out.

Restricting to https seems OK. Or calling the https on the server side from the http.

If that is not satisfactory. It would probably not take too much work to move the small amount of "state" held by the Phylesystem wrapper to use redis instead of memory. Or even not caching that info in memory.

**Comment by mtholder** [comment]
@jimallman Can we close this? We are just redirecting http to https, right?

**Comment by jimallman** [comment]
Yes, and we've not seen this monster since. Closing!
