### ISSUE TITLE
iterating over studies

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/peyotl#134]
I am trying to iterate over studies, and running into issues with methods that I _think_ used to work. With `scripts/ot_phylesystem_list_tags.py`, I get:

`AttributeError: '_Phylesystem' object has no attribute 'iter_study_objs'`

and with `scripts/ot_phylesystem_list_study_filepaths.py` I get:

`ImportError: cannot import name phylesystem_study_paths`

If I try and copy what's on the [github.io](http://opentreeoflife.github.io/peyotl/phylesystem/) site, I get:

`AttributeError: '_Phylesystem' object has no attribute 'iter_study_filepaths'`

Any ideas about whether something has changed, or if I am doing something silly? I am happy to update the scripts / docs if necessary.

**Comment by jimallman** [comment]
Hm, possibly a casualty of the refactoring refactoring for collections? I'll pursue this shortly (putting out other fires at the moment)...

**Comment by jimallman** [comment]
OK, I've put some fixes in the PR above. Please try these and let me know if this needs more attention!
