### ISSUE TITLE
Normalize DOI reference when importing from treebase; clean up existing phylesystem.

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/peyotl#138]
_This was originally submitted by @jar398 to the 'opentree' repo, but it's really a peyotl issue._

E.g. ot_303 has "^prism:doi": "10.1038/ncomms5473", which comes from treebase, but when it is imported to studyPublication it becomes
"@href": "10.1038/ncomms5473"
which is wrong - all studyPublication values should be URLs, and furthermore if they are DOIs they should start with http://dx.doi.org/.

I think the normalization works well elsewhere, and that this problem only occurs on treebase import.

This affects 58 studies. They will have to be fixed.

**Comment by mtholder** [comment]
this shouldn't be hard to deal with. During the peyotl refactoring, I definitely need to look at the treebase imports some more.

**Comment by jimallman** [comment]
Thanks! In the meantime, I'll tweak the (read-only) Metadata tab to coerce a simple DOI into a working hyperlink (or omit the hyperlink if it's not a DOI). This will avoid the confusion of clicking the link and going... nowhere.

**Comment by jimallman** [comment]
The PR above is working now on **devtree**. It alleviates most client-side bugs by either converting DOIs to URLs where appropriate, or showing simple strings instead of invalid hyperlinks. Of course, we should go ahead with fixing these during TreeBASE import and for all existing studies in phylesystem (which can now be accomplished by simply opening each in the curation app, then saving).

**Comment by jimallman** [comment]
For a more permanent fix, see the existing (probably helpful) `doi2url` function mentioned in https://github.com/OpenTreeOfLife/clade-workshops/issues/5#issuecomment-249990134

**Comment by jar398** [comment]
The coercion should only happen when creating the nexson for a treebase study, not when the nexson comes from some other source. For other sources a valid nexson should be required (i.e. an invalid nexson should be rejected), and a valid nexson has URLs where URLs are expected. See comment under #155. 

I see this is already merged, sorry. Not high priority to change this.
