### ISSUE TITLE
Script to collect list of tree / study properties

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/peyotl#139]
For the new oti, want to be able to search by any tree or study property. Would like to find these from the nexsons, rather than hard-code the list. Code should probably live in `peyotl/nexson_syntax/__init__.py`. Of course, not sure about keeping this up to date (noting that this happens with the current system, too, so writing such a script does not create a new problem).

**Comment by jar398** [comment]
looks to me like this is related to #137 ... if all properties were available from the NexsonProxy the script would be trivial.
Rather than worry about keeping lists of property names up to date, the script could simply be driven off of all unstructured properties.

**Comment by jar398** [comment]
This is not related to # 137.

**Comment by kcranston** [comment]
Going to put this in the newoti code, since it is only relevant to search / indexing.

**Comment by kcranston** [comment]
Script is [here](https://github.com/OpenTreeOfLife/ottreeindex/blob/master/dev_scripts/get_study_tree_properties.py)
