### ISSUE TITLE
Method to get name of taxon

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/peyotl#141]
Given an OTT id I would like to learn the name of the taxon. I see in ott/\_\_init\_\_.py that there's a name2id table that gets pickled, but I don't see any methods for making use of that table.

**Comment by kcranston** [comment]
Looks like we can use [ott_id_to_names](https://github.com/OpenTreeOfLife/peyotl/blob/a91833404b6e84ac33ebbc176296bdf9a2c698fc/peyotl/ott/__init__.py#L406) which returns a tuple with the canonical name as the first element.
