### ISSUE TITLE
Quieter verification that no update is needed

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/peyotl#150]
It's hard to look for errors, and be satisfied that there are none, when there are mountains of script output.  When I do a webapp update using the deployment system, something does a 'make' of peyotl, which leads to a 'make' of ncl. This leads to about 400 lines of output.  If it were 20, I think that would be very nice. Of course errors should be shown, but I don't need to know that it is entering and leaving directories in order to do nothing.

**Comment by mtholder** [comment]
NCL is used by the curator app not peyotl. You could put an issue in NCL to make the Makefile quieter. but (with my "primary maintainer of NCL" hat on) I don't think rewriting NCL's makefiles (which are generated by automake and autoconf) is going to happen anytime soon.
